function [B, NB] = My_FIR (Fpass, Fstop, Astop)
    %MY_FIR Returns a discrete-time filter object.
    
    % MATLAB Code
    % Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
    % Generated on: 05-Nov-2024 10:42:07
    
    % Equiripple Lowpass filter designed using the FIRPM function.
    
    % All frequency values are in Hz.
    Fs = 48000;  % Sampling Frequency
    
    % Fpass = 8000;            % Passband Frequency
    % Fstop = 12000;           % Stopband Frequency
    Dpass = 0.057501127785;  % Passband Ripple
    Dstop = 10^(-Astop/20);  % Stopband Attenuation
    dens  = 20;              % Density Factor
    
    % Calculate the order from the parameters using FIRPMORD.
    [N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
    
    % Calculate the coefficients using the FIRPM function.
    b  = firpm(N, Fo, Ao, W, {dens});
    Hd = dfilt.dffir(b);
    B=Hd.Numerator;
    NB=length(B);
    
    end
% [EOF]